import { ConnectorRegistry } from "./connectorRegistry.js";
import { CredentialVault } from "../security/credentialVault.js";
import { VaultSecretSummary } from "../security/credentialVault.js";

export interface ConnectorSetupRequirement {
  name: string;
  scope: string;
  configured: boolean;
  description: string;
}

export interface ConnectorSetupProfile {
  connectorId: string;
  name: string;
  ready: boolean;
  enabled: boolean;
  description?: string;
  requiredSecrets: ConnectorSetupRequirement[];
  steps: string[];
  metadata: Record<string, unknown>;
}

export interface SaveSetupSecretInput {
  connectorId: string;
  name: string;
  value: string;
  description?: string;
}

const descriptions: Record<string, Record<string, string>> = {
  openai: { OPENAI_API_KEY: "OpenAI API key used by planner/provider connector calls." },
  ghl: { GHL_API_KEY: "GoHighLevel private integration token or API key.", GHL_LOCATION_ID: "Optional GHL location/sub-account id for contact searches and workflow actions." },
  gmail: { GOOGLE_CLIENT_ID: "Google OAuth client id.", GOOGLE_CLIENT_SECRET: "Google OAuth client secret.", GOOGLE_REFRESH_TOKEN: "Google OAuth refresh token with Gmail draft permissions.", GOOGLE_ACCESS_TOKEN: "Short-lived access token; can be generated by the refresh tool." },
  calendar: { GOOGLE_CLIENT_ID: "Google OAuth client id.", GOOGLE_CLIENT_SECRET: "Google OAuth client secret.", GOOGLE_REFRESH_TOKEN: "Google OAuth refresh token with Calendar event permissions.", GOOGLE_ACCESS_TOKEN: "Short-lived access token; can be generated by the refresh tool." },
  stripe: { STRIPE_SECRET_KEY: "Stripe restricted secret key for read-only account checks or safe adapter calls." }
};

function fallbackDescription(connectorId: string, name: string): string {
  return descriptions[connectorId]?.[name] || `Required secret for ${connectorId}.`;
}

export class ConnectorSetupWizard {
  constructor(private readonly registry: ConnectorRegistry, private readonly vault: CredentialVault) {}

  list(): ConnectorSetupProfile[] {
    return this.registry.list().map((status) => this.profile(status.id));
  }

  profile(connectorId: string): ConnectorSetupProfile {
    const status = this.registry.status(connectorId);
    const requiredSecrets = (status.requiredSecrets || []).map((name) => ({
      name,
      scope: connectorId,
      configured: this.vault.has(name, connectorId) || this.vault.has(name, "workspace"),
      description: fallbackDescription(connectorId, name)
    }));
    const missing = requiredSecrets.filter((item) => !item.configured).map((item) => item.name);
    const steps = [
      status.enabled ? "Connector is enabled in config." : "Enable the connector in config/connectors.json when ready.",
      missing.length ? `Add missing vault secret(s): ${missing.join(", ")}.` : "All required vault secrets are present.",
      status.agentAllowlistActive ? `Review agent allowlist: ${(status.allowedAgents || []).join(", ")}.` : "Optional: add allowedAgents to restrict which agents can use this connector.",
      "Run connector health check.",
      "Prepare a dry-run action before enabling real execution."
    ];
    return {
      connectorId: status.id,
      name: status.name,
      ready: status.ready,
      enabled: status.enabled,
      description: status.description,
      requiredSecrets,
      steps,
      metadata: status.metadata || {}
    };
  }

  saveSecret(input: SaveSetupSecretInput): VaultSecretSummary {
    const status = this.registry.status(input.connectorId);
    const required = status.requiredSecrets || [];
    if (!required.includes(input.name)) {
      throw new Error(`Secret '${input.name}' is not listed as required for connector '${input.connectorId}'.`);
    }
    return this.vault.set({
      name: input.name,
      value: input.value,
      scope: input.connectorId,
      provider: input.connectorId,
      description: input.description || fallbackDescription(input.connectorId, input.name)
    });
  }
}
